---
title: "Reproducible Data Analysis"
toc: false
---

## Slides

- [Day 1 (2024-06-06): Introduction: Why code? Why reproducibility?](day1/index.qmd)

- [Day 2 (2024-06-13): Git and GitHub](day2/index.qmd)

- [Day 3 (2024-06-20): Basic usage of R and RStudio](day3/index.qmd)

- [Day 4 (Media Day): Data loading and tidying with tidyverse](day4/index.qmd)

- [Day 5 (Media Day): Joining data](day5/index.qmd)

- [Day 6 (2024-07-08): Data visualization with ggplot2](day6/index.qmd)

- [Day 7 (2024-07-11): Writing documents with Quarto](day7/index.qmd)

<!-- - [Day 8 (2024-07-18): Quarto, part II](day8/index.qmd) -->

- Day 8 (2024-07-18): Quarto, part II

## Recordings

(video recordings are not available for all lectures)

- [Day 4: Tidyverse](https://youtu.be/ikzQwRJbh18?si=tiv94i5X_LJF6uqr)

<!--
- [Day 5: Data tidying, part II](https://youtu.be/n06QEKese5U)
-->

## Materials

- [Day 2: Git and GitHub](https://github.com/data-analysis-chiba-2024/day02-git/blob/main/day02_intro_to_git.md)

- [Day 3: R and RStudio](https://github.com/data-analysis-chiba-2024/day03-r/blob/main/day03_intro_to_r.md)

- [Day 4: Tidyverse, part I](https://github.com/data-analysis-chiba-2024/day04-tidy/blob/main/day04_tidy.md)

- [Day 5: Joining data (R for Data Science)](https://r4ds.hadley.nz/joins)

- [Day 6: ggplot2](https://github.com/data-analysis-chiba-2024/day06-ggplot/blob/main/day06_ggplot2.md)

- [Final Report Example](https://github.com/data-analysis-chiba-2024/gapminder-report/)

## Important Deadlines

- 2024-06-19 11:59PM: [Day 2 homework](https://github.com/data-analysis-chiba-2024/day02-git/blob/main/git_facts.md) due

- 2024-06-26 11:59PM: [Day 3 homework](https://github.com/data-analysis-chiba-2024/day03-r/blob/main/day03_homework.R) due

- 2024-07-03 11:59PM: [Day 4 homework](https://github.com/data-analysis-chiba-2024/day04-tidy/blob/main/day04_homework.R) due

- 2024-07-10 11:59PM: [Day 5 homework](https://github.com/data-analysis-chiba-2024/day05-join/blob/main/day05_homework.R) due

- 2024-07-24 11:59PM: Final paper due

## Office Hours

By appointment, please send an email to <joelnitta@chiba-u.jp>

## Syllabus

[Syllabus in English](https://syllabus.gs.chiba-u.jp/2024/101101101076000/Z011531301/en_US)
